logLevel = "INFO"
defaultEntryPoints = ["https","http"]

[api]

[entryPoints]
  [entryPoints.http]
  address = ":80"
  [entryPoints.http.redirect]
  entryPoint = "https"
  [entryPoints.https]
  address = ":443"
  [entryPoints.https.tls]

[retry]

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "maincoin.money"
watch = true
exposedbydefault = false

[acme]
email = "support@maincoin.money"
storage = "/home/explorer/acme.json"
entryPoint = "https"
OnHostRule = true
usebindportip = true
acmeLogging = true 
onDemand = false #create certificate when container is created
  [acme.dnsChallenge]
  provider = "cloudflare"
  delayBeforeCheck = 0
  [[acme.domains]]
   main = "maincoin.money"
  [[acme.domains]]
   main = "*.maincoin.money"
  [acme.httpChallenge]
  entryPoint = "http"
